### PR TITLE
modulize the sfta.py for further extension

### PR DESCRIPTION
**Pull request by KMerdan**
I found your code very useful but a bit difficult to read and maintain, so I made some improvements to enhance its readability and maintainability.

Main Changes:

- Modularized `sfta.py`
- Added a Streamlit GUI

This PR is not perfect, but I ensured that all tests pass. I believe this is a good starting point.

### CODE REVIEW

**Comment by yawnoc** [comment]
Thank you for your efforts!

I will need some time (a few weekends) to review the changes (and to properly acknowledge your contributions in the readme) before I merge into master.

Are you happy for me to push further edits (mostly style/whitespace tweaks) onto [KMerdan:master](https://github.com/KMerdan/sfta/tree/master)?

~~(If not, please change the target branch of this pull request to modular-with-gui and I'll merge and make the further edits there.)~~

**Comment by KMerdan** [comment]
Yes, it would be better if you could merge it back. 
I didn't know how much effort you wanted to put into maintaining it, so I just made quick and dirty modifications. If you have any style or linting guidelines you want me to follow in future work, we can set up a CI for that.

**Comment by KMerdan** [comment]
hey, would you be able to check out this PR  https://github.com/KMerdan/sfta/pull/1 if it is what you want, otherwise i will keep it to myself

**Comment by KMerdan** [comment]
i think you dont need this anymore.

**Comment by yawnoc** [comment]
Apologies for not following up yesterday before [merging different edits to master](https://github.com/yawnoc/sfta/commit/c93a6eb2841797652e2241ac94b0a6a80a59649e).

After reviewing this pull request:

1. I decided I could not accept the addition of Streamlit as a GUI (519e24d). Streamlit prompts for the user's email on first run, and I have no confidence that it respects developer & user privacy based on the maintainers' responses (or lack thereof) to the questions raised in the following issues:
   - https://github.com/streamlit/streamlit/issues/4747
   - https://github.com/streamlit/streamlit/issues/5996
   - https://github.com/streamlit/streamlit/issues/7202
   - https://github.com/streamlit/streamlit/issues/8098

1. Separately, I felt that the modularisation (78c402d) went too far; the need to extract out specific class constants (to prevent circular imports) was a symptom of this. Nevertheless, based on the pull request, I performed my own refactor that landed in the middle ground between the original (everything in one file) and the pull request (almost every class in a separate file).

Nevertheless, I thank you very much for raising this pull request. Without it, SFTA would still be an unpackaged single-file script.

~~The next release will expose the `FaultTree` class so that it can be imported (that you may hook it up to any GUI you like). I will let you know when that is done.~~

**Pull request closed without merging**
